language: go

go:
  - 1.4
  - 1.5
  - 1.6
  - 1.7

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

services:
  - rabbitmq

env:
 - AMQP_URI=amqp://guest:guest@127.0.0.1:5672/

script:
  - ./coverall.sh
